#!/bin/bash
[ ! -x "$(command -v jsonschema)" ] && pip3 install jsonschema

_exit=0
for example_file in $(ls -1 examples/*.json)
do
  echo "jsonschema -i $example_file ${example_file/example/schema}"
  jsonschema -i $example_file ${example_file/example/schema}
  [ $? != 0 ] && _exit=1
done

exit $_exit
